version: "3.0"

services:
  postdb:
    container_name: postdb
    image: postgres:latest
    volumes:
      - dbvolume:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postdb
volumes:
  dbvolume: 
