name: CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create the digital library network
        working-directory: ./aplicacao
        run: docker network create biblioteca_digital

      - name: Build the digital app library
        working-directory: ./aplicacao
        run: docker-compose up -d

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create the digital library network
        working-directory: ./aplicacao
        run: docker network create biblioteca_digital

      - name: Install and run rubocop/lint
        working-directory: ./aplicacao
        run: docker-compose run app bash -c "gem install rubocop; rubocop --fail-level F"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create the digital library network
        working-directory: ./aplicacao
        run: docker network create biblioteca_digital

    - name: Reset db and run rspec
      working-directory: ./aplicacao
      run: docker-compose run app bash -c "rails db:reset; rspec"
